In [1]:
import pandas as pd

df = pd.read_csv("../results/cell_type_reference_from_panglao_to_wikidata_31_10_2020.csv")

In [2]:
alias_en = df["panglao"]

alias_en = ["human " + alias for alias in alias_en]

alias_en = [alias.lower() for alias in alias_en]


label_en = alias_en

replacements = {
    "cells" : "cell",
    "neurons" : "neuron",
    "cytes" : "cyte",
    "lasts" : "last",
    "elets" : "elet",
    "phils" : "phil"
}

for replacement in replacements:
    label_en = [label.replace(replacement, replacements[replacement]) for label in label_en]
    
df["Len"] = label_en
df["Aen"] = alias_en

In [3]:
df["Den"] = "cell type of Homo sapiens"

df["Dpt"] = "tipo de célula de Homo sapiens"

df["P361"] = df["wikidata"]

df["P703"] = "Q15978631" # found in human
df["P31"] = "Q18911" # instance of cell type

In [4]:
df = df.drop(["wikidata", "panglao"], axis=1)
df = df.dropna()
df.head()

,Unnamed: 0,Len,Aen,Den,Dpt,P361,P703,P31
0,0,human basal cell,human basal cells,cell type of Homo sapiens,tipo de célula de Homo sapiens,Q101062513,Q15978631,Q18911
1,1,human trigeminal neuron,human trigeminal neurons,cell type of Homo sapiens,tipo de célula de Homo sapiens,Q101062590,Q15978631,Q18911
2,2,human juxtaglomerular cell,human juxtaglomerular cells,cell type of Homo sapiens,tipo de célula de Homo sapiens,Q2596226,Q15978631,Q18911
3,3,human pancreatic stellate cell,human pancreatic stellate cells,cell type of Homo sapiens,tipo de célula de Homo sapiens,Q1164962,Q15978631,Q18911
4,4,human fibroblast,human fibroblasts,cell type of Homo sapiens,tipo de célula de Homo sapiens,Q463418,Q15978631,Q18911

In [5]:
df.to_csv("../data/human_cell_types_to_add_08_11_2020.csv", index=False )

In [6]:
with open("../quickstatements/add__human_cell_types_08_11_2020.qs", "w+") as qs:

    for i, row in df.iterrows():

        s = "LAST"

        Len = s + "|Len|" + '"' + row["Len"] + '"' + "\n"
        Den = s +"|Den|" + '"' + row["Den"] + '"' + "\n"
        Dpt = s +"|Dpt|" + '"' + row["Dpt"] + '"' + "\n"
        Aen = s +"|Aen|" + '"' + row["Aen"] + '"' + "\n"
        P31 = s + "|P31|" + row["P31"] + "|S248|" + "Q99936939" +   "\n" 
        P703 = s + "|P703|" + row["P703"] + "\n"
        P361 = s + "|P361|" + row["P361"] + "\n"

        qs.write('CREATE \n')
        qs.write(Len)
        qs.write(Den)
        qs.write(Dpt)
        qs.write(Aen)
        qs.write(P31)
        qs.write(P703)
        qs.write(P361)
        qs.write('\n')

Added to Wikidata via Quickstatements